on:
  push:

jobs:
  vitest213:
    name: Vitest 2.1.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm install 'vitest@2.1.3' '@vitest/browser@2.1.3'
      - run: npx playwright install --with-deps
      - run: npx vitest

  vitest214:
    name: Vitest 2.1.4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm install 'vitest@2.1.4' '@vitest/browser@2.1.4'
      - run: npx playwright install --with-deps
      - run: npx vitest
